name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}  # ensure 'app' is importable everywhere

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Prepare DB (init + seed)
        run: |
          python scripts/init_db.py
          python scripts/seed_from_sample.py

      - name: Lint
        run: flake8 app ingest scripts tests streamlit_app.py

      - name: Tests
        run: pytest -q
